version: '3.9'
services:
  deployer:
    container_name: file_uploader_deployer
    build:
      context: docker/deployer
    platform: linux/amd64
    volumes:
      - './:/var/deployer'
    working_dir: '/var/deployer'
    command: [ '/bin/sh', '-c', 'tail -f /dev/null' ]
    env_file:
      - .env
    restart: always
